# Medidas de dispersão {#md}

## Introdução

Iniciamos esse capítulo, motivados por três conjuntos de dados que resultaram em mesma média aritmética propositalmente. Vejamos o Código R a seguir. Esse código apresenta uma simulação de três grupos com 10 observações cada um. Os grupos formados foram `gA`, `gB` e `gC`, com suas respectivas médias $\bar{X}_{\textrm{gA}} = 9,018686$ unid., $\bar{X}_{\textrm{gB}} = 9,018686$ unid. e $\bar{X}_{\textrm{gC}} = 9,018686$ unid., respectivamente. Dessa forma, poderíamos concluir que os grupos de dados são iguais? A resposta é não. Isso significa, que essa medida de posição apenas não consegue caracterizar completamente os grupos de dados.

```{r meddisp, collapse=TRUE}
# Semente de simulação
# set.seed(10)

# Dados dos grupos gerados
set.seed(10); gA <- rnorm(10, mean = 10, sd = 2)
set.seed(10); gB <- rnorm(9, mean = 10, sd = 4)
set.seed(10); gC <- rnorm(9, mean = 10, sd = 6)

# Media do grupo gA
(media.gA <- mean(gA))

# gerando gB[10] e media de gB
gB[10] <- gB10 <- length(gA) * media.gA - sum(gB)
(media.gB <- mean(gB))


# gerando gC[10] e media de gC
gC[10] <- gc10 <- length(gA) * media.gA - sum(gC)
(media.gC <- mean(gC))

# Apresentando os dados
gA; gB; gC
```

Os dados para os três grupos são apresentados na Tabela \@ref(tab:tresgrupos). Ao observarmos com mais detalhes os valores observados nos grupos, percebemos que estes não são iguais. Logo, poderíamos erroneamente afirmar que estes grupos eram semelhantes, simplemente olhando para as suas médias. O que ocorre é uma variabilidade nos dados diferenciada em cada grupo, e que a medida de dispersão não consegue caracterizá-la. Dizemos que variabilidade é a dispersão com que ocorre nos dados, e as medidas responsáveis em expressar essa variabilidade, chamamos na estatística descritiva de medidas de dispersão. Geralmente, usamos a representação dessa dispersão em torno de um valor central nos dados, que em nosso caso, será a média aritmética, devido a algumas propriedades matemáticas e estatísticas que essa medida tem, e que será vista ao longo de todo o livro.

<style type="text/css">
.tg  {border-collapse:collapse;border-color:#93a1a1;border-spacing:0;}
.tg td{background-color:#fdf6e3;border-bottom-width:1px;border-color:#93a1a1;border-style:solid;border-top-width:1px;
  border-width:0px;color:#002b36;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;
  word-break:normal;}
.tg th{background-color:#657b83;border-bottom-width:1px;border-color:#93a1a1;border-style:solid;border-top-width:1px;
  border-width:0px;color:#fdf6e3;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;
  padding:10px 5px;word-break:normal;}
.tg .tg-baqh{text-align:center;vertical-align:top}
</style>
<table class="tg">
<caption>(\#tab:tresgrupos) Dados dos três grupos simulados pelo Código R.</caption>
<thead>
  <tr>
    <th class="tg-baqh">gA</th>
    <th class="tg-baqh">gB</th>
    <th class="tg-baqh">gC</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-baqh">$10,037492$</td>
    <td class="tg-baqh">$10,074985$</td>
    <td class="tg-baqh">$10,1124770$</td>
  </tr>
  <tr>
    <td class="tg-baqh">$9,631495$</td>
    <td class="tg-baqh">$9,262990$</td>
    <td class="tg-baqh">$8,8944847$</td>
  </tr>
  <tr>
    <td class="tg-baqh">$7,257339$</td>
    <td class="tg-baqh">$4,514678$</td>
    <td class="tg-baqh">$1,7720167$</td>
  </tr>
  <tr>
    <td class="tg-baqh">$8,801665$</td>
    <td class="tg-baqh">$7,603329$</td>
    <td class="tg-baqh">$6,4049937$</td>
  </tr>
  <tr>
    <td class="tg-baqh">$10,589090$</td>
    <td class="tg-baqh">$11,178181$</td>
    <td class="tg-baqh">$11,7672708$</td>
  </tr>
  <tr>
    <td class="tg-baqh">$10,779589$</td>
    <td class="tg-baqh">$11,559177$</td>
    <td class="tg-baqh">$12,3387658$</td>
  </tr>
  <tr>
    <td class="tg-baqh">$7,583848$</td>
    <td class="tg-baqh">$5,167695$</td>
    <td class="tg-baqh">$2,7515429$</td>
  </tr>
  <tr>
    <td class="tg-baqh">$9,272648$</td>
    <td class="tg-baqh">$8,545296$</td>
    <td class="tg-baqh">$7,8179439$</td>
  </tr>
  <tr>
    <td class="tg-baqh">$6,746655$</td>
    <td class="tg-baqh">$3,493309$</td>
    <td class="tg-baqh">$0,2399639$</td>
  </tr>
  <tr>
    <td class="tg-baqh">$9,487043$</td>
    <td class="tg-baqh">$18,787223$</td>
    <td class="tg-baqh">$28,0874035$</td>
  </tr>
  <tr>
    <td class="tg-baqh">$\bar{X}_{\textrm{gA}} = 9,018686$</td>
    <td class="tg-baqh">$\bar{X}_{\textrm{gB}} = 9,018686$</td>
    <td class="tg-baqh">$\bar{X}_{\textrm{gC}} = 9,018686$</td>
  </tr>
</tbody>
</table>

A seguir, mostraremos algumas medidas de dispersão que auxiliarão na caracterização dos dados, bem como no auxílio a fundamentação de temas tão importantes como a inferência estatística e teoria de decisão, abordado em capítulos posteriores.


## Amplitude total ou Amplitude

A primeira medida de dispersão que definiremos é a amplitude ou amplitude total, denotada por $A$ ou $A_t$. Iremos apresentar, três definições sobre a amplitude baseadas nos valores observados da população, da amostra, e em dados agrupados sem e com intervalo de classe. Vejamos o primeiro caso, pensando em uma população, apresentada na (\#def:amppop).

<div id="def:amppop" class="definicao" cap=4 titulo="(Amplitude em uma população)">
Seja uma população $X_1$, $X_2$, $\ldots$, $X_N$, de tamanho$N$, e em ordem crescente de magnitude temos $X_{(1)} = \min\limits_{i}(X_i)$, $X_{(2)}$, $\ldots$, $X_{(N)} = \max\limits_{i}(X_i)$, para $i$ $=$ $1$, $2$, $\ldots$, $N$. Então a amplitude de uma população, denotada por $A_p$, é definida por:
  \begin{align}
    A_p & = X_{(N)} - X_{(1)}. (\#eq:amppop)
  \end{align}
</div>

Se desejarmos representar essa notação em termos de valor observado, temos $a_t = x_{(N)} - x_{(1)}$. Já usamos uma referência sobre a amplitude total ou amplitude, expressão \@ref(eq:amptotal), quando agrupamos os dados em intervalo de classes, para o caso das variáveis quantitativas contínuas. Vejamos o (\#exm:amazlegal) sobre os dados da taxa de desmatamento na Amazônia legal, compreendido entre 1988 a 07/12/2020.

<div id="exm:amazlegal" class="exemplo" cap=4 titulo="Desmatamento da Amazônia Legal">
Já mencionamos anteriormente, na Tabela \@ref(tab:amazlegal), os dados de desmatamento da Amazônia legal. Se considerarmos que os elementos da população sejam os estados, portanto, temos as informações de todos os elementos, e assim, estamos diante de dados populacionais. Vamos assim, calcular a amplitude para a variável desmatamento acumulado, em $km^2$, de acordo com a expressão \@ref(eq:amptotal), isto é,
\begin{align*}
  A & = 157.667,00 - 1.696,00 = 155971~km^2.
\end{align*}
Isso representa, uma variação de $155971~km^2$. Observe que essa medida está na mesma escala da variável, e que se houve um outro conjunto de dados, em mesma unidade, poderíamos comparar qual a que apresentou maior dispersão.
</div>

Podemos representar a aplitude em termos amostras, como será apresentado na (\#def:ampamostra), a seguir.

<div id="def:ampamostra" class="definicao" cap=4 titulo="(Amplitude em uma amostra)">
Seja uma amostra $X_1$, $X_2$, \ldots, $X_n$, de tamanho $n$, e em ordem crescente de magnitude temos $X_{(1)} = \min\limits_{i}(X_i)$, $X_{(2)}$, \ldots, $X_{(n)} = \max\limits_{i}(X_i)$, para $i$ $=$ $1$, $2$, $\ldots$, $n$. Então a amplitude de uma população, denotada por $A$, é definida por:
  \begin{align}
    A & = X_{(n)} - X_{(1)}. (\#eq:ampamostral)
  \end{align}
</div>

O que vai diferenciar a representação nas expressões \@ref(eq:amppop) e \ref(eq:ampamostral), e o número de elementos, isto é, o tamanho populacional representado por "$N$", e o tamanho amostral, representado por "$n$". Porém, percebemos que a realização do cálculo é a mesma. Da mesma forma que a representação populacional, podemos representar a amplitude em uma amostra, em termos de valor observado como $a = x_{(n)} - x_{(1)}$. Vejamos o (\#exm:dadosim), a seguir.

<div id="exm:dadosim" class="exemplo" cap=4 titulo="">
Retornando aos dados amostrais simulados na Tabela \@ref(tab:tresgrupos), calculamos as amplitudes,

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-c3ow">Grupo</th>
    <th class="tg-c3ow">Amplitude</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">`gA`</td>
    <td class="tg-0pky">$A = 10,77959 - 6,746655 = 4,032934~und.$</td>
  </tr>
  <tr>
    <td class="tg-0pky">`gB` </td>
    <td class="tg-0pky">$A = 18,787223 - 3,493309 = 15,29391~und.$</td>
  </tr>
  <tr>
    <td class="tg-0pky">`gC`</td>
    <td class="tg-0pky">$A = 28,0874035 - 0,2399639 = 15,29391~und.$</td>
  </tr>
</tbody>
</table>
Por esse resultado, podemos observar os grupos `gB` e `gC` que suas amplitudes foram iguais. Será que podemos, então afirmar que esses dois grupos são iguais? Quando observamos os dados, percebemos que os valores não são iguais. Isso ocorre por uma limitação nessa medida de dispersão. Vamos deixar para explorar essa situação mais a frente.
</div>

Para a amplitude em termos de dados agrupados, temos a situação em que as variáveis podem ser discretas ou contínuas. No caso, das variáveis quantitativas contínuas, os grupos são classes, e os valores passam a ser representados pelos seus pontos médios de cada classe. Assim, apresentamos na (\#def:ampagrupado), a aplitude para dados agrupados com e sem intervalo de classe.

<div id="def:ampagrupado" class="definicao" cap=4 titulo="(Amplitude em dados agrupados)">
Seja uma amostra $X_1$, $X_2$, \ldots, $X_n$, de tamanho $n$, agrupados em $k$ grupos com variáveis $X_i$ e $F_i$ frequências, ou $k$ classes com pontos médios $\tilde{X}_i$ e $F_i$ frequências, para $i$ $=$ $1$, $2$, $\ldots$, $k$ e $\sum_{i = 1}^{k}F_i = n$, então a amplitude de uma amostra, denotada por $A$, é definida por:
  \begin{align}
    A & = \left\{\begin{array}{ll}
                   X_{(k)} - X_{(1)}, &  \textrm{Agrupados sem intervalo de classe}, \\
                   \tilde{X}_{(k)} - \tilde{X}_{(1)}, & \textrm{Agrupados com intervalo de classe},\\
                 \end{array}\right. (\#eq:ampagrupados)
  \end{align}
  em que $X_{(k)} = \max\limits_{i}(X_i)$, $X_{(1)} = \min\limits_{i}(X_i)$, $\tilde{X}_{(k)} = \max\limits_{i}(\tilde{X}_{i})$, $\tilde{X}_{(1)} = \min\limits_{i}(\tilde{X}_{i})$, sendo $\tilde{X}_{i}$ o ponto médio das classes.
</div>

Podemos representar a Definição \@ref(def:ampagrupado) em termos populacionais, substituindo o tamanho $n$ por $N$, como também representar a expressão em termos de valor observado, como mencionado na definições  anteriores. Vejamos o (\#exm:dadosampagrupados), a seguir.

<div id="exm:dadosampagrupados" class="exemplo" cap=4 titulo="">
Retornando aos dados da Tabela \@ref(tab:erroscanaldf), podemos calcular a amplitude do número de erros encontrados em 20 conjunto de caracteres, usando a expressão \@ref(eq:ampagrupados), da seguinte forma:
\begin{align*}
  A & = 4 - 1 = 3~\textrm{erros}.
\end{align*}
Para os dados agrupados com intervalo de classe, apresentados no Exemplo \@ref(exm:Challanger1986), podemos calcular a amplitude da temperatura do anel de vedação de cada teste de acionamento do motor do foguete Challanger, da seguinte forma:
\begin{align*}
  A & = 84 - 31 = 52~\textrm{°F}.
\end{align*}
No primeiro caso, usamos as próprias observações para o cálculo da amplitude. No segundo caso, usamos os pontos médios.
</div>

Podemos ainda apresentar algumas características sobre a amplitude, dos quais temos:

- o resultado da amplitude é dado na mesma unidade da variável em estudo;
- uma medida de dispersão facilmente calculada;
- limitada apenas as variáveis quantitativas;
- essa medida é muito utilizada em comparações múltiplas, cartas de controle em estatística de qualidade, dentre outras áreas;
- a amplitude pode ser utilizada como medida de dispersão para comparar a variabilidade de dados de dois ou mais grupos diferentes;
- a amplitude é sensível a dados discrepantes^[Entendemos por dados discrepantes, as observações que estão distantes da massa de dados (maior parte dos dados). Esses dados quando influenciam as análises estatísticas, dizemos que estes dados são influentes.];
- a amplitude é limitada por levar em consideração apenas os valores extremos, e nada sobre as demais observações. Nesse caso, podem ocorrer situações como os apresentados no Exemplo \@ref(exm:dadosim), em que poderíamos erroneamente concluir que os grupos de dados `gB` e `gC` são iguais, uma vez que apresentam amplitude e média aritmética iguais;
-  segundo @Ferreira2009, a amplitude amostral, expressão \@ref(eq:ampamostral), substima a amplitude populacional, expressão \@ref(eq:amppop), uma vez que é pouco provável que uma amostra contenha os valores mínimo e máximo da população, portanto, a amplitude amostral é um estimador^[Entendemos por estimador uma função que depende apenas dos dados amostrais e que irá representar um parâmetro (característica populacional) desconhecida.] viesado^[Dizemos que um estimador é viesado se a esperança matemática desse estimador é diferente do parâmetro de interesse.] e ineficiente.

Complementando as características da amplitude, apresentamos algumas propriedades pelo (\#thm:amplitude) a seguir, do qual iremos usar a Definição \@ref(def:ampamostra) como base, e as demais seguem de forma similar.

<div id="thm:amplitude" class="teorema" cap=4 titulo="Propriedades da Amplitude">
Baseado na Definição \@ref(def:ampamostra), e considerando $c$ uma constante, então:

I) Se para uma amostra $X_1$, $X_2$, \ldots, $X_n$, a amplitude é dada por $A_X = X_{(n)} - X_{(1)}$, então para uma transformação de $Y_i = X_i \pm c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$,  a nova amplitude não se altera, isto é, $A_Y = A_X$.
II) Se para uma amostra $X_1$, $X_2$, \ldots, $X_n$, a amplitude é dada por $A_X = X_{(n)} - X_{(1)}$, então para uma transformação de $Y_i = X_i \times c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, a nova amplitude é dada por $A_Y = A_X \times c$. Esse resultado vale também para a transformação $Y_i = X_i / m$, sendo $m$ também uma constante. Basta usar $c = 1 / m$ e o resultado é o mesmo.
</div>

<div id="prova:amplitude" class="prova" cap=1 titulo="">
I) Considerando uma amostra $X_1$, $X_2$, \ldots, $X_n$, e $c$ uma constante, e que $Y_i = X_i \pm c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então a amplitude de $Y_i$ é dado por:
  \begin{align*}
    A_Y & = Y_{(n)} - Y_{(1)}\\
        & = (X_{(n)} \pm c)  - (X_{(1)} \pm c)\\
        & = X_{(n)}  - X_{(1)}\\
        & = A_X. \quad \textrm{c.q.d.}
  \end{align*}
II) Considerando uma amostra $X_1$, $X_2$, \ldots, $X_n$, e $c$ uma constante, e que $Y_i = X_i \times c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então a amplitude de $Y_i$ é dado por:
  \begin{align*}
    A_Y & = Y_{(n)} - Y_{(1)}\\
        & = (X_{(n)} \times  c)  - (X_{(1)} \times c)\\
        & = (X_{(n)}  - X_{(1)}) \times c\\
        & = A_X \times c. \quad \textrm{c.q.d.}
  \end{align*}
</div>

Devido ao problema encontrado no Exemplo \@ref(exm:dadosim), vamos apresentar algumas outras medidas que levem em consideração as demais variáveis bem como uma referência da posição central dos dados, que em nosso caso será a média aritmética.

## Variância

Diante do Exemplo \@ref(exm:dadosim), percebemos que complementar a caracterização dos dados com a amplitude, se torna uma medida muito simples. Observamos que os grupos `gB` e `gC` apresentam mesmas médias e amplitudes. Assim, poderíamos dizer que os grupos são semelhantes. Mas quando observamos a Tabela \@ref(tab:tresgrupos), percebemos que estes são diferentes. Assim, vamos apresentar mais algumas medidas que englobem as demais variáveis e o valor central desses dados em seu cálculo, para apresentarmos medidas mais explicativas para dispersão de dados.

Considerando uma população $X_1$, $X_2$, $\ldots$, $X_N$ e sua respectiva amostra $X_1$, $X_2$, $\ldots$, $X_n$, podemos considerar inicialmente o desvio médio como outra medida de dispersão, dada por:

\begin{align}
  DM_p & = \sum_{i = 1}^{N} \left(X_i - \mu \right), \quad \textrm{(Populacional)} (\#eq:desvmediopop)
\end{align}
em que $\mu = \sum_{i = 1}^{N} X_i / N$, e seu respectivo estimador é dado por:
\begin{align}
  DM & = \sum_{i = 1}^{n} \left(X_i - \bar{X} \right), \quad \textrm{(Amostral)} (\#eq:desvmedioamost)
\end{align}
em que $\bar{X} = \sum_{i = 1}^{n} X_i / n$. Observamos agora, que diferentemente da amplitude, essa medida leva em consideração todos os elementos, seja da amostra ou da população, em relação a uma medida central, como preconizamos inicialmente a definição de uma medida de dispersão no início desse capítulo. O problema é que a expressão \@ref(eq:desvmedioamost), como mostrado no Teorema \@ref(thm:PropSom), propriedade (V), sempre resulta em valor nulo para qualquer grupo amostral. De modo similar, a expressão \@ref(eq:desvmediopop) também $\sum_{i = 1}^{N} \left(X_i - \mu \right) = 0$. Isso significa que essa medida não traz ganho algum a descrição dos dados, porque os desvios positivos anulam-se com os desvios negativos no somatório, sendo pois uma questão de problema algébrico. Para isso, podemos contornar essa situação inserindo uma função modular nessa medida anterior, e criar o módulo do desvio, dada por:
\begin{align}
  S_{|\mu|} & = \sum_{i = 1}^{N} \left|X_i - \mu \right|, \quad \textrm{(Populacional)} (\#eq:desvmodpop)
\end{align}
e
\begin{align}
  S_{|\bar{X}|} & = \sum_{i = 1}^{n} \left|X_i - \bar{X} \right|. \quad \textrm{(Amostral)} (\#eq:desvmodamost)
\end{align}

Desse modo, sabemos que $\sum_{i = 1}^{n} \left|X_i - \bar{X} \right| \geq 0$, e agora temos uma medida que represente a dispersão com o qual os dados estão em torno da média. Quanto maior o módulo do desvio, mais disperso é o conjunto de dados. A questão do uso do módulo para resolver o problema da medida do desvio médio, nos gera uma outra dificuldade que poderemos ter mais a frente quando formos estudar inferência estatística. Tem situações que iremos precisar integrar, derivar, etc., dentre outras ferramentas matemáticas, que se torna mais fácil ao invés de usar o módulo, usarmos uma função quadrática na medida. Daí, surge uma outra medida de variabilidade que é a soma de quadrados, dada por:
\begin{align}
  SQ_{p} & = \sum_{i = 1}^{N} \left(X_i - \mu \right)^2, \quad \textrm{(Populacional)} (\#eq:desvquadpop)
\end{align}
e
\begin{align}
  SQ & = \sum_{i = 1}^{n} \left(X_i - \bar{X} \right)^2. \quad \textrm{(Amostral)} (\#eq:desvquadamost)
\end{align}
Percebemos que a soma de quadrados amostral pode ser também expressa por:
\begin{align}
  SQ & = \displaystyle\sum_{i = 1}^{n}X_i^2 - \frac{1}{n} \sum_{i = 1}^{n}X_i^2, (#eq:desvquadamost2)
\end{align}
como pode ser provado no Teorema \@ref(thm:PropSom). Nesse último caso, podemos trabalhar sem o uso da informação da média, mas sim, apenas com as informações das observações. Essa medida apresenta uma outra informação interessante que é penalizar as observações quanto mais estiver distante do valor central. Observe que quando elevamos ao quadrado um alto desvio, esse valor se torna maior ainda, mas quando elevamos ao quadrado um desvio pequeno, esse valor não cresce tanto. Assim, conseguimos compreender quais os dados que estão mais dispersos em torno da média.

Baseado nessas informações, surge a variância populacional que é a média da soma de quadrados, denotada por $\sigma^2$, apresentada na (\#def:varpop).

<div id="def:varpop" class="definicao" cap=4 titulo="(Variância de uma população)">
Seja uma população $X_1$, $X_2$, $\ldots$, $X_N$, de tamanho $N$, com parâmetro conhecido $\mu = \sum_{i = 1}^{N} X_i / N$, então a variância populacional, denotada por $\sigma^2$, é definida por:
  \begin{align}
    \sigma^2 & = \frac{SQ_p}{N}, (\#eq:varpop1)
  \end{align}
  em que $SQ_p$ é dado pela expressão \@ref(eq:desvquadpop), ou de forma similar,
  \begin{align}
    \sigma^2 & = \frac{\displaystyle\sum_{i = 1}^{N}X_i^2 - \frac{1}{N} \sum_{i = 1}^{N}X_i^2}{N}. (\#eq:varpop2)
  \end{align}
</div>

Podemos de forma intuitiva, pensar no estimador para $\sigma^2$ simplesmente substituindo ``$N$'' por ``$n$'' e $SQ_p$ por $SQ$, usando as mesmas expressões do que foram usados na Definição \@ref(def:varpop), isto é,
\begin{align}
  \hat{\sigma}^2 & = \frac{SQ}{n}. (\#eq:varamost1)
\end{align}

Porém, existe uma propriedade nos estimadores, vista mais a frente, que é o seu viés. Dizemos que estimadores são viesados quando a sua esperança matemática não é igual ao parâmetro de interesse. Significa dizer em termos práticas, que mesmo se nós retirássemos todas as $k$ amostras possíveis de uma população e para cada uma dessas amostras calculássemos a variância amostral, expressão \@ref(eq:varamost1), e posteriormente a média dessas variâncias, ou seja, $(\hat{\sigma}^2_1 +\hat{\sigma}^2_2 + \ldots + \hat{\sigma}^2_k) / k$, esse valor não seria igual a $\sigma^2$. Logo, $\hat{\sigma}^2$ é um estimador viesado. De outro modo, é um estimador defeituoso. Para contornar esse problema, usamos a seguinte definição para uma variância amostral não viesada, denotada por $S^2$, e apresentada na (\#def:varamost).

<div id="def:varamost" class="definicao" cap=4 titulo="(Variância de uma amostra)">
  Seja uma população $X_1$, $X_2$, $\ldots$, $X_n$, de tamanho $n$, com $\bar{X} = \sum_{i = 1}^{n} X_i / n$, então a variância amostral, denotada por $S^2$, é definida como:
  \begin{align}
    S^2 & = \frac{SQ}{n - 1}, (\#eq:varamost2)
  \end{align}
  em que $SQ$ é dado pela expressão \@ref(eq:desvquadamost), ou de forma similar,
  \begin{align}
    S^2 & = \frac{\displaystyle\sum_{i = 1}^{n}X_i^2 - \frac{1}{n} \sum_{i = 1}^{n}X_i^2}{n - 1}. (\#eq:varamost3)
  \end{align}
</div>

Para elucidar essas informações, vejamos o (\#exm:dadosimvar).

<div id="exm:dadosimvar" class="exemplo" cap=4 titulo="">
Retornando aos dados amostrais simulados na Tabela \@ref(tab:tresgrupos), podemos calcular a variância amostral para cada um dos grupos. Vamos usar a expressão \@ref(eq:varamost3) para isso, que segue:

- Variância amostral para o grupo `gA`:
  \begin{align*}
    S^2_{\textrm{gA}} & = \frac{10,037492^2 + \ldots + 9,487043^2 - 1 / 9 \times \left(10,037492 +  \ldots + 9,487043 \right)^2}{9 - 1}\\
                    & = \frac{831,0017 - 8133.67 / 9}{8}\\
                    & = 1,959404~und^2
  \end{align*}
- Variância amostral para o grupo `gB`:
\begin{align*}
    S^2_{\textrm{gB}} & = \frac{10,074985^2 + \ldots + 18,787223^2 - 1 / 9 \times \left(10,074985 +  \ldots + 18,787223 \right)^2}{9 - 1}\\
                    & = \frac{988,9577 - 8133.67 / 9}{8}\\
                    & = 19,51007~und^2
\end{align*}
- Variância amostral para o grupo `gC`:
  \begin{align*}
    S^2_{\textrm{gC}} & = \frac{10,1124770^2 + \ldots + 28,0874035^2 - 1 / 9 \times \left(10,1124770 +  \ldots + 28,0874035 \right)^2}{9 - 1}\\
                    & = \frac{1373,903 - 8133.67 / 9}{8}\\
                    & = 62,28176~und^2
\end{align*}

Podemos perceber que de fato os grupos `gB` e `gC` não são iguais, como podem verificar pelas suas variâncias amostrais, uma vez que isso poderia ter ocorrido pelo resultado do Exemplo \@ref(exm:dadosim). A dispersão das informações se torna mais detalhado, porque agora a medida leva em consideração a todas as observações.
</div>

Para o caso de dados agrupados, apresentamos a seguir a notação para o cálculo da variância, pela  (\#def:varagrupado).

<div id="def:varagrupado" class="definicao" cap=4 titulo="(Variância em dados agrupados)">
Seja uma amostra $X_1$, $X_2$, $\ldots$, $X_n$, de tamanho $n$, agrupados em $k$ grupos com variáveis $X_i$ e frequência $F_i$, ou $k$ classes com pontos médios $\tilde{X}_i$ e $F_i$ frequências, para $i$ $=$ $1$, $2$, $\ldots$, $k$ e $\sum_{i = 1}^{k}F_i = n$, então a variância de uma amostra, denotada por $S^2$, é definida por:
\begin{align}
    S^2 & = \left\{\begin{array}{ll}
                   \frac{\sum_{i = 1}^{k}(X_i - \bar{X})^2\times F_i}{\sum_{i = 1}^{k}F_i - 1}, &  \textrm{agrupados sem intervalo de classe}, \\
                   &\\
                   \frac{\sum_{i = 1}^{k}(\tilde{X}_i - \bar{\tilde{X}})^2\times F_i}{\sum_{i = 1}^{k}F_i - 1}, &  \textrm{agrupados com intervalo de classe},\\
                 \end{array}\right. (\#eq:varagrupados)
  \end{align}
  sendo $\tilde{X}_{i}$ o ponto médio das classes, $\bar{X} = \sum_{i = 1}^{k} X_iF_i / \sum_{i = 1}^{k}F_i$ e $\bar{\tilde{X}} = \sum_{i = 1}^{k} \tilde{X}_iF_i / \sum_{i = 1}^{k}F_i$, ou se forma similar,
\begin{align}
    S^2 & = \left\{\begin{array}{ll}
                  \frac{\sum_{i = 1}^{k}X_i^2\times F_i - \frac{1}{\sum_{i = 1}^{k} F_i}(\sum_{i = 1}^{k} X_iF_i)^2}{\sum_{i = 1}^{k}F_i - 1}, &  \textrm{agrupados sem intervalo de classe}, \\
                  & \\
                  \frac{\sum_{i = 1}^{k}\tilde{X}_i^2\times F_i - \frac{1}{\sum_{i = 1}^{k} F_i}(\sum_{i = 1}^{k} \tilde{X}_iF_i)^2}{\sum_{i = 1}^{k}F_i - 1}, &  \textrm{agrupados com intervalo de classe}. \\
                 \end{array}\right. (\#eq:varagrupados2)
  \end{align}
</div>

Podemos representar a Definição \@ref(def:varagrupado) em termos populacionais, substituindo o tamanho $n$ por $N$ e considerando o denominador apenas como $\sum_{i = 1}^{k}F_i - 1$ ao invés de $\sum_{i = 1}^{k}F_i - 1$, tal que $\sum_{i = 1}^{k}F_i = N$. Podemos também representar a expressão em termos de valor observado, como mencionado na definições  anteriores.

Vejamos algumas características da variância:

- a unidade da variância está na escala ao quadrado da unidade da variável;
- limitada apenas as variáveis quantitativas;
- a variância é sempre uma medida positiva, exceto quando todos os valores são iguais que resultam em uma variância nula;
- quanto mais próximo de zero a variância for, mas concentrado os dados estão em torno da média, ao passo que, à medida que a variância se distancia de zero, mas disperso os dados estão em torno da média;
- devido as suas propriedades matemáticas, algumas mencionadas anteriormente, bem como a quantidade de técnicas estatísticas que empregam essa medida, a torna como a mais conhecida dentre as medidas de dispersão;
- uma vez que a média é sensível aos dados, a variância também é sensível, uma vez que esta depende da média.

Pelo (\#thm:variancia), apresentamos algumas propriedades da variância a seguir, do qual iremos usar a Definição \@ref(def:varamost) como base, e as demais seguem de forma similar.

<div id="thm:variancia" class="teorema" cap=4 titulo="Propriedades de somatório">
Baseado na Definição \@ref(def:varamost), e considerando $c$ uma constante, então:

I) Se para uma amostra $X_1$, $X_2$, $\ldots$, $X_n$, a variância é dada por $S^2_X$, expressão \@ref(eq:varamost2), então para uma transformação de $Y_i = X_i \pm c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então a nova variância não se altera, isto é, $S^2_Y = S^2_X$.
II) Se para uma amostra $X_1$, $X_2$, $\ldots$, $X_n$, a variância é dada por $S^2_X$, expressão \@ref(eq:varamost2), então para uma transformação de $Y_i = X_i \times c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então a nova variância é dada por $S^2_Y = c^2\times S^2_X$. Esse resultado vale também para a transformação $Y_i = X_i / m$, sendo $m$ também uma constante. Basta usar $c = 1 / m$ e o resultado é o mesmo.
</div>

<div id="prova:PropSom" class="prova" cap=1 titulo="">
I) Considerando uma amostra $X_1$, $X_2$, \ldots, $X_n$, e $c$ uma constante, e que $Y_i = X_i \pm c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então a variância de $Y_i$ é dado por:
\begin{align*}
    S^2_Y & = \frac{\sum_{i = 1}^{n}(Y_i - \bar{Y})^2}{n - 1}\\
        & = \frac{\sum_{i = 1}^{n}[(X_i \pm c) - (\bar{X} \pm c)]^2}{n - 1}\\
         & = \frac{\sum_{i = 1}^{n}(X_i - \bar{X})^2}{n - 1}\\
        & = S^2_X. \quad \textrm{c.q.d.}
\end{align*}
II) Considerando uma amostra $X_1$, $X_2$, \ldots, $X_n$, e $c$ uma constante, e que $Y_i = X_i \times c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então a variância de $Y_i$ é dado por:
\begin{align*}
    S^2_Y & = \frac{\sum_{i = 1}^{n}(Y_i - \bar{Y})^2}{n - 1}\\
        & = \frac{\sum_{i = 1}^{n}[(X_i \times c) - (\bar{X} \times c)]^2}{n - 1}\\
        & = \frac{\sum_{i = 1}^{n}c^2(X_i - \bar{X})^2}{n - 1}\\
        & = c^2 \times \frac{\sum_{i = 1}^{n}(X_i - \bar{X})^2}{n - 1}, \quad \textrm{(Teorema 1.1, (I))}\\
        & = c^2 \times S^2_X. \quad \textrm{c.q.d.}
\end{align*}

</div>

## Desvio padrão

A variância apesar de ter resolvido alguns dos problemas mencionados anteriormente, para uma medida de dispersão, apresenta sua unidade ao quadrado da unidade da variável em estudo, isso significa que se tivermos usando uma variável na escala de metros, a dispersão dada pela variância estará na escala de área, isto é, em metros ao quadrado. Isso se torna difícil a percepção de dispersão quando observamos os dados. Dessa forma, surge a medida do desvio padrão, (\#def:desvpad).

<div id="def:desvpad" class="definicao" cap=4 titulo="(Desvio padrão)">
Seja uma amostra $X_1$, $X_2$, $\ldots$, $X_n$, de uma população $X_1$, $X_2$, $\ldots$, $X_N$, de tamanhos $n$ e $N$, respectivamente, com parâmetro  $\mu = \sum_{i = 1}^{N} X_i / N$ e seu estimador $\bar{X} = \sum_{i = 1}^{n} X_i / n$, então o desvio padrão é definido por:
  \begin{align}
    \sigma & = \sqrt{\sigma^2}, \quad \textrm{(População)} (\#eq:desvpad1)
  \end{align}
  em que $\sigma$ é apresentado na Definição \@ref(def:varpop),
  \begin{align}
    S & = \sqrt{S^2}, \quad \textrm{(Amostra)} (\#eq:desvpad2)
  \end{align}
  em que $S$ é apresentado na Definição \@ref(def:varamost).
</div>

Com o desvio padrão, podemos verificar a medida de variabilidade na mesma unidade da variável. Cabe destacar que a expressão \@ref(eq:desvpad1) mede a variabilidade das observações em torno da média populacional. Porém na prática, não conhecemos o parâmetro $\mu$ nem muito menos temos informações de todas as observações. Com isso usamos como estimador de $\sigma$, o desvio padrão amostral dado na expressão \@ref(eq:desvpad2), que se baseia em apenas uma amostra. Vejamos o (\#exm:dadosimvar).

<div id="exm:dadosimvar" class="exemplo" cap=4 titulo="">
Retornando ao Exemplo \@ref(dadosim), podemos então calcular os desvios padrões dos grupos, que segue:

- Desvio padrão amostral para o grupo `gA`:
\begin{align*}
    S_{\textrm{gA}} & = \sqrt{1,959404} = 1,399787~unid.
  \end{align*}
- Desvio padrão amostral para o grupo `gB`:
\begin{align*}
    S_{\textrm{gB}} & = \sqrt{19,51007} = 4,41702~und.
  \end{align*}
- Desvio padrão amostral para o grupo `gC`:
  \begin{align*}
   S_{\textrm{gC}} & = \sqrt{62,28176} = 7,89188~und.
\end{align*}

Considerando que as unidades dos grupos são iguais, bem como as suas médias, podemos concluir que o grupo `gA` apresenta menor dispersão. Claro que esse resultado, poderia ter sido observado pela variância. A diferença é que conseguimos entender na unidade da variável essa dispersão.
</div>

Contudo, quando iremos comparar grupos de dados e verificar qual grupo apresenta maior variabilidade, devemos ter muito cuidado ao usar o desvio padrão ou a variância, sob dois aspectos:

- Os grupos de observações devem estar na mesma unidade de mensuração;
- A média desses grupos devem ser iguais.

O primeiro aspecto está muito claro, uma vez que não temos, por exemplo, como comparar uma unidade em gramas e saber se a dispersão desses dados é maior ou menor quando se compara com outro conjunto de dados cuja unidade esteja na escala de comprimento. O segundo aspecto está limitado devido a forma de como foram calculados o desvio padrão e a variância. A soma de seus desvios levam em consideração a média. Assim, quando comparamos dois desvios padrões de duas amostras de uma população, em que temos o desvio padrão $S^2_1 = 10~unid$ para a amostra 1, e $S^2_2 = 20~unid$ para a amostra 2. Não podemos afirmar que a amostra 2 apresenta maior dispersão que a amostra 1, isso porque não sabemos o quanto esse valor representa em relação a média. Supomos que a média da amostra 1 seja $\bar{X}_1 = 100~unid$ e para a amostra 2, seja  $\bar{X}_1 = 50~unid$. Desse modo, observemos que para a amostra 1, o desvio padrão representa apenas 10\% do valor da média. Já na amostra 2, o desvio padrão representa 40\% da média, uma variação muito mais considerável, isto é, os dados na amostra 2 são muito mais dispersos em torno da média. Isso justifica então, a criação de uma medida de dispersão relativa à média, que será definida na próxima seção.

Vejamos algumas características do desvio padrão, que segue:

- a unidade do desvio padrão está na mesma escala da unidade da variável em estudo;
- limitada apenas as variáveis quantitativas;
- uma vez que a média é sensível aos dados, o desvio padrão também é sensível, uma vez que esta depende da média;
- embora a variância amostral, $S^2$ seja um estimador não viesado para a variância populacional $\sigma^2$, o desvio padrão amostral $S$, que é derivado de $S^2$, é um estimador viesado do desvio padrão populacional $\sigma$;
- assim como a variância, o desvio padrão é sempre uma medida positiva, exceto quando todos os valores são iguais que resultam em uma variância nula;
- assim como na variância, quanto mais próximo de zero o desvio padrão for, mas concentrado os dados estão em torno da média, ao passo que, à medida que o desvio padrão se distancia de zero, mas disperso os dados estão em torno da média.

Complementando as características do desvio padrão, apresentamos algumas propriedades no (\#thm:amplitude), do qual iremos usar a Definição \@ref(def:ampamostra) como base, e as demais seguem de forma similar.

<div id="thm:desvpad" class="teorema" cap=4 titulo="Propriedades do Desvio padrão">
Baseado na Definição \@ref(def:ampamostra), e considerando $c$ uma constante, então:

I) Se para uma amostra $X_1$, $X_2$, \ldots, $X_n$, a amplitude é dada por $A_X = X_{(n)} - X_{(1)}$, então para uma transformação de $Y_i = X_i \pm c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então o novo desvio padrão não se altera, isto é, $S_Y = S_X$.
II) Se para uma amostra $X_1$, $X_2$, \ldots, $X_n$, a amplitude é dada por $A_X = X_{(n)} - X_{(1)}$, então para uma transformação de $Y_i = X_i \times c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então a nova amplitude é dada por $A_Y = A_X \times c$. Esse resultado vale também para a transformação $Y_i = X_i / m$, sendo $m$ também uma constante. Basta usar $c = 1 / m$ e o resultado é o mesmo.
</div>

<div id="prova:desvpad" class="prova" cap=1 titulo="">
I) Considerando uma amostra $X_1$, $X_2$, \ldots, $X_n$, e $c$ uma constante, e que $Y_i = X_i \pm c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então o desvio padrão de $Y_i$ é dado por:
\begin{align*}
    S_Y & = \sqrt{\frac{\sum_{i = 1}^{n}(Y_i - \bar{Y})^2}{n - 1}}\\
        & = \sqrt{\frac{\sum_{i = 1}^{n}[(X_i \pm c) - (\bar{X} \pm c)]^2}{n - 1}}\\
         & = \sqrt{\frac{\sum_{i = 1}^{n}(X_i - \bar{X})^2}{n - 1}}\\
        & = S_X. \quad \textrm{c.q.d.}
\end{align*}
II) Considerando uma amostra $X_1$, $X_2$, \ldots, $X_n$, e $c$ uma constante, e que $Y_i = X_i \times c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então a variância de $Y_i$ é dado por:
\begin{align*}
    S_Y & = \sqrt{\frac{\sum_{i = 1}^{n}(Y_i - \bar{Y})^2}{n - 1}}\\
        & = \sqrt{\frac{\sum_{i = 1}^{n}[(X_i \times c) - (\bar{X} \times c)]^2}{n - 1}}\\
        & = \sqrt{\frac{\sum_{i = 1}^{n}c^2(X_i - \bar{X})^2}{n - 1}}\\
        & = \sqrt{c^2\frac{\sum_{i = 1}^{n}(X_i - \bar{X})^2}{n - 1}}, \quad \textrm{(Teorema 1.1, (I))}\\
        & = c \times \sqrt{S^2_X},\\
        & = c \times S_X. \quad \textrm{c.q.d.}
\end{align*}
</div>

## Coeficiente de Variação

As medidas de variabilidade tais como a variância e desvio padrão, são conhecidas como medidas de dispersão absoluta. Diante do que foi exposto no fim da seção anterior sobre alguns problemas do desvio padrão, apresentamos mais uma medida de dispersão, (\#def:coefvar), agora uma medida relativa chamada de Coeficiente de Variação (CV), do qual pode ser usada para comparar a variabilidade entre quaisquer grupo de dados.

<div id="def:coefvar" class="definicao" cap=4 titulo="(Coeficiente de Variação)">
Seja uma amostra $X_1$, $X_2$, $\ldots$, $X_n$, de uma população $X_1$, $X_2$, $\ldots$, $X_N$, de tamanhos $n$ e $N$, respectivamente, com parâmetros  $\mu = \sum_{i = 1}^{N} X_i / N$ e $\sigma^2 = \sum_{i = 1}^{N}(X_i - \mu)^2 / (N - 1)$ e seus estimadores $\bar{X} = \sum_{i = 1}^{n} X_i / n$ e $S = \sqrt{\sum_{i = 1}^{n}(X_i - \bar{X})^2 / (n - 1)}$, respectivamente. Então o coeficiente de variação é definido por:
\begin{align}
    CV_p & = \frac{\sigma}{\mu} \times 100, \quad \textrm{(População)} (\#eq:cvpop)
\end{align}
  e
\begin{align}
    CV & = \frac{S}{\bar{X}} \times 100. \quad \textrm{(Amostra)} (\#eq:cvamost)
\end{align}
</div>

Essa medida permite com que possamos comparar a dispersão com dois ou mais grupos com características completamente diferente e com médias diferentes. Vejamos o (\#exm:dadoscoefvar), para ilustrar essa característica.

<div id="exm:dadoscoefvar" class="exemplo" cap=4 titulo="">
  Com a medida do coeficiente de variação, podemos comparar a dispersão dos dados do Exemplo \@ref(tab:erroscanal) com a dispersão do grupo `gA` da Tabela \@ref(tab:tresgrupos). Para o primeiro conjunto de dados, podemos calcular a média e o desvio padrão do número de erros encontrados em 20 conjuntos de caracteres, dados por:
\begin{align*}
    \bar{X}_e & = \frac{3 + 1 + \ldots + 1}{20} = 1,7~\textrm{erros},
\end{align*}
  e
\begin{align*}
    S_e & = \sqrt{\frac{3^2 + 1^2 + \ldots + 1^2 - 1 / 20 \times (3 + 1 + \ldots + 1)^2}{19}}\\
      & = 1,174286~\textrm{erros},
\end{align*}
respectivamente. No caso dos dados do grupo `gA`, nós já temos os resultados da média e desvio padrão, dados na Tabela \@ref(tab:tresgrupos) e no Exemplo \@ref(exm:dadosimvar), respectivamente. Desse modo, comparando a dispersão dos dois grupos pelo coeficiente de variação, temos:

<style type="text/css">
.tg  {border-collapse:collapse;border-color:#93a1a1;border-spacing:0;}
.tg td{background-color:#fdf6e3;border-bottom-width:1px;border-color:#93a1a1;border-style:solid;border-top-width:1px;
  border-width:0px;color:#002b36;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;
  word-break:normal;}
.tg th{background-color:#657b83;border-bottom-width:1px;border-color:#93a1a1;border-style:solid;border-top-width:1px;
  border-width:0px;color:#fdf6e3;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;
  padding:10px 5px;word-break:normal;}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky">Dados</th>
    <th class="tg-c3ow">Coeficiente de Variação ($CV$)</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">`gA`</td>
    <td class="tg-0pky">$CV_{\textrm{gA}} = \frac{1,399787}{9,018686} \times 100 = 15,52\%$</td>
  </tr>
  <tr>
    <td class="tg-0pky">Número de erros<br></td>
    <td class="tg-0pky">$CV_{e} = \frac{1,174286}{1,7} \times 100 = 69,08\%$</td>
  </tr>
</tbody>
</table>

Nesse caso, percebemos que os dados de `gA` tem menor variabilidade do que os dados do número de erros, e com isso, esses dados são melhor representado pela sua média amostral quando se comparado com o outro grupo de dados.
</div>

Mesmo resolvendo alguns problemas existentes nas medidas variância e desvio padrão, o coeficiente de variação apresenta  algumas características importantes, que seguem:

- O $CV$ é adimensional e uma medida de dispersão relativa;
- Essa medida pode ser utilizada para comparar a dispersão entre grupos diferentes de dados;
- Como o $CV$ é uma medida de dispersão relativa, isto é, o desvio padrão ponderado pela média. Isso significa que o $CV$ calcula o quanto representa a dispersão (o desvio padrão) representa à média. Dessa forma, o $CV$ se torna limitado a variáveis em que a escala de mensuração das observações em que fornece um zero absoluto ou uma origem significativa. Por exemplo, a temperatura em graus celsius (ºC), uma observação igual a 0ºC não significa ausência de temperatura, logo, o $CV$ para esse tipo de variável não faz sentido. Já o a variável peso em quilos, isto é, o valor 0kg representa ausência de peso, de outro modo, esse tipo de variável permite magnitudes de valores na escala, tais como, uma observação de 40kg é o dobro de uma observação de 20kg. Assim, podemos utilizar o coeficiente de variação para verificar a dispersão da variável peso;
- O $CV$ pode superar o 100\%. Isso ocorre quando o desvio padrão é maior do a média. Dizemos que esses superdispersos, um exemplo, são dados de contagem que seguem uma distribuição de Poisson.

As propriedades do $CV$  levam em consideração as propriedade de $\bar{X}$ e $S$, que já foram demonstradas. Assim, ficam para estudo no Exercício proposto [4.1](#exr:Ex4.1), a demonstração para as propriedades do $CV$.

## Erro padrão da média

Para iniciarmos uma última ideia sobre medidas de dispersão, dentre as medidas básicas, vamos iniciar como motivação, a (\#def:erroamost).

<div id="def:erroamost" class="definicao" cap=4 titulo="(Erro amostral da média)">
Seja uma amostra $X_1$, $X_2$, $\ldots$, $X_n$, de uma população com parâmetro  $\mu$, que representa a média populacional, e seu estimador $\bar{X} = \sum_{i = 1}^{n} X_i / n$, então definimos o erro da média amostral, denotado por $EA_{\bar{X}}$, da seguinte forma:
  \begin{align}
    EA_{\bar{X}} & = \bar{X} - \mu. (\#eq:erroamost)
  \end{align}
</div>

A medida expressa em \@ref(eq:erroamost) representa o erro de assumirmos a média amostral como um representante da média populacional. O desvio padrão de $EA_{\bar{X}}$ é o que chamamos de erro padrão da média, definido a seguir.

<div id="def:erropadpop" class="definicao" cap=4 titulo="(Erro padrão da média - Populacional)">
Seja uma amostra $X_1$, $X_2$, $\ldots$, $X_n$, de uma população cujos parâmetros $\mu$ e $\sigma$, representam a média e o desvio padrão populacional, respectivamente, então o erro padrão da média, denotada por $\sigma_{\bar{X}}$, é definido como:
  \begin{align}
    \sigma_{\bar{X}} & = \frac{\sigma}{\sqrt{n}}, (\#eq:epmediapop)
  \end{align}
  em que $n$ representa o tamanho da amostra.
</div>

Quando fazemos um comparativo entre o desvio padrão amostral e o erro padrão da média, entendemos que a primeira medida reflete a variabilidade de cada observação em torno da média amostral. Já o erro padrão da média representa a variabilidade de cada média amostral de todas  amostra possíveis, em relação a média populacional.

Dessa forma, surgem alguns problemas para determinar a variabilidade da
média amostral em torno da média populacional usando a expressão \@ref(eq:epmediapop). Primeiro, é praticamente
impossível realizar todas as amostras possíveis de uma população para computar a sua média. Se isso é possível, não precisaremos de amostra, uma vez que temos todas as informações da população, e então, estamos diante de um censo. Os outros fatores, podemos destacar que na prática, realizamos apenas uma amostra para análise das informação, e que o desvio padrão populacional geralemente é desconhecido, e assim, torna-se inviável o cálculo de $\sigma_{\bar{X}}$. Uma alternativa é usar o estimador $S$ ao invés de $\sigma$, surgindo então um estimador para o erro padrão da média populacional, definido a seguir.

<div id="def:erropadpop" class="definicao" cap=4 titulo="(Erro padrão da média - Amostral)">
Seja uma amostra $X_1$, $X_2$, $\ldots$, $X_n$, de uma população cujos parâmetros $\mu$ e $\sigma$, representam a média e o desvio padrão populacional, respectivamente, então o erro padrão da média, denotada por $\sigma_{\bar{X}}$, é definido como:
  \begin{align}
    S_{\bar{X}} & = \frac{S}{\sqrt{n}}, (\#eq:epmediapop)
  \end{align}
  em que $n$ representa o tamanho da amostra, e $S$ é o desvio padrão da Definição \@ref(def:desvpad).
</div>

É fácil observar que à medida que $n \to N$, isto é, à medida que $n$ aumenta, a média amostral tende a $\mu$, logo o $EA_{\bar{X}} \to 0$. Isso significa que a média amostral é mais precisa porque se aproxima cada vez mais da média populacional. Assim, com apenas uma amostra poderemos ter uma estimativa do erro padrão da média, em que veremos um exemplo a seguir.

<div id="exm:exemerropadrao" class="exemplo" cap=4 titulo="Trajédia das barragens de rejeito">
Retornando ao Exemplo \@ref(exm:dadosim), podemos então calcular os erros padrões da média para as três amostras, que segue:

- Erro padrão da média amostral para o grupo `gA`:
  \begin{align*}
    S_{\bar{X}_{\textrm{gA}}} & = 1,399787 / \sqrt{9} = 0,4665957~unid.
  \end{align*}
- Erro padrão da média amostral para o grupo `gB`:
  \begin{align*}
    S_{\bar{X}_{\textrm{gB}}} & = 4,41702 / \sqrt{9} = 1,47234~und.
  \end{align*}
- Erro padrão da média amostral para o grupo `gC`:
  \begin{align*}
   S_{\bar{X}_{\textrm{gC}}} & = 7,89188 / \sqrt{9} = 2,630627~und.
  \end{align*}

Percebemos que a média de `gA` estima melhor o parâmetro $\mu$, uma vez que o erro padrão da média foi o menor dentre os demais.
</div>

Desse modo, observamos que o erro padrão da média representa uma precisão com que a média amostral estimou o parâmetro $\mu$. Além do erro padrão da média, há diversos outros erros padrões para outros estimadores de parâmetros diversos, sendo abordado mais a frente. Além do mais, essa medida será largamente usada na teoria de estimação e de decisão, tanto para a construção de intervalos de confiança, como também no desenvolvimento de testes de hipóteses, sendo também abordado nos próximos capítulos.

## Exercícios propostos {-}


<div id="exr:Ex4.1" class="exerprop" cap=4 titulo="">
Com relação as propriedades do Coeficiente de Variação (CV), prove que:

I) Se para uma amostra $X_1$, $X_2$, \ldots, $X_n$, o coeficiente de variação, Definição \ref{def:coefvar}, então para uma transformação de $Y_i = X_i \pm c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então o novo coeficiente de variação é igual a $CV_Y = S / (\bar{X} \pm c) \times 100$.
II) Se para uma amostra $X_1$, $X_2$, $\ldots$, $X_n$, o coeficiente de variação, Definição \@ref(def:coefvar), então para uma transformação de $Y_i = X_i \times c$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, então o novo coeficiente de variação não se altera, isto é $CV_Y = CV_X$. Esse resultado vale também para a transformação $Y_i = X_i / m$, sendo $m$ também uma constante. Basta usar $c = 1 / m$ e o resultado é o mesmo.
</div>

<div id="exr:Ex4.2" class="exerprop" cap=4 titulo="">
A tabela abaixo apresenta a distribuição de frequências das notas (em pontos) obtidas num teste de matemática, realizado por 50 estudantes.
\
<style type="text/css">
.tg  {border-collapse:collapse;border-color:#93a1a1;border-spacing:0;}
.tg td{background-color:#fdf6e3;border-bottom-width:1px;border-color:#93a1a1;border-style:solid;border-top-width:1px;
  border-width:0px;color:#002b36;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;
  word-break:normal;}
.tg th{background-color:#657b83;border-bottom-width:1px;border-color:#93a1a1;border-style:solid;border-top-width:1px;
  border-width:0px;color:#fdf6e3;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;
  padding:10px 5px;word-break:normal;}
.tg .tg-baqh{text-align:center;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-baqh">Notas</th>
    <th class="tg-baqh">$F_i$</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0lax">0 $|$--- 2</td>
    <td class="tg-baqh">4</td>
  </tr>
  <tr>
    <td class="tg-0lax">2 $|$--- 4</td>
    <td class="tg-baqh">12</td>
  </tr>
  <tr>
    <td class="tg-0lax">4 $|$--- 6</td>
    <td class="tg-baqh">15</td>
  </tr>
  <tr>
    <td class="tg-0lax">6 $|$--- 8</td>
    <td class="tg-baqh">13</td>
  </tr>
  <tr>
    <td class="tg-0lax">8 $|$--- 10</td>
    <td class="tg-baqh">6</td>
  </tr>
</tbody>
</table>

Apresente o cálculo para todas as medidas de dispersão estudadas e as interprete.
</div>

<div id="exr:Ex4.3" class="exerprop" cap=4 titulo="">
Para uma amostra $X_1$, $X_2$, $\ldots$, $X_n$ de tamanho $n$. Desejamos usar a transformação
$Y_i = \beta_0 + \beta_1X_i$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, considerando $\beta_0$ e $\beta_1$ constantes. Então, apresente as relação entre as médias e os desvios padrões de $X$ e $Y$.
</div>

<div id="exr:Ex4.4" class="exerprop" cap=4 titulo="">
Sabemos que a conversão da temperatura de graus Celsius (ºC) para a escala de Fahrenheit (ºF) é dada por: $F = 9 / 5 \times C + 32$, considerando a variável $F$ a temperatura em Fahrenheit, e $C$ a temperatura em graus Celsius. Se medíssemos a temperatura de um peça no momento de fabricação, e verificássemos que em média a peça é fabricada com temperatura de $70$ºC e variância de $2(^oC)^2$, como poderíamos representar essas medidas na escala Fahrenheit?
</div>

<div id="exr:Ex4.5" class="exerprop" cap=4 titulo="">
Se tivéssemos estudando as a variável temperatura em três escalas: graus Celsius, Fahrenheit e Kelvin, poderíamos calcular o coeficiente de variação para as três escalas? Explique.
</div>

<div id="exr:Ex4.6" class="exerprop" cap=4 titulo="">
Considere uma amostra $X_1$, $X_2$, $\dots$, $X_n$ de tamanho $n$, do qual conseguimos computar a média aritmética e variância amostral, sendo representadas por $\bar{X}_n$ e $S^2_n$, respectivamente, e que esses índices representam que estas medidas foram calculadas baseadas em um tamanho de amostra $n$. Por alguma situação precisamos adicionar mais uma variável a esta amostra, isto é, a variável $X_{n+1}$. Como poderíamos calcular as medidas $\bar{X}_{n+1}$ e $S^2_{n+1}$, partindo do pressuposto que só sabemos das informações $\bar{X}_n$, $S^2_n$ e $X_{n+1}$? Em um segundo momento considere o Exemplo \@ref(exm:Challanger1986), os dados sem agrupamento de classes, de modo que foi realizado uma nova medição da temperatura do anel de vedação no acionamento do foguete Challenger, sendo aferido o valor $x_{37}=63$ºF, use os resultados obtidos e determine $\bar{x}_{n+1}$ e $s^2_{n+1}$ após desse novo dado as observações.
</div>

<div id="exr:Ex4.7" class="exerprop" cap=4 titulo="">
Considere uma amostra $X_1$, $X_2$, $\dots$, $X_n$ de tamanho $n$, do qual conseguimos computar as medidas de posição $\bar{X}$, $Md(X)$ e $Mo(X)$, isto é, a média, mediana e moda, respectivamente, bem como a variância $S^2_X$. Considere também as transformações $Y_i = X_i - \bar{X}$ e $Z_i = (X_i - \bar{X}) / S$, para $i$ $=$ $1$, $2$, $\ldots$, $n$, sendo $S = \sqrt{S^2}$. Apresente as medidas de dispersão, desvio padrão e variância, para essas transformações, $Y$ e $Z$.
</div>

